POST https://node-do-zero-dwb5.onrender.com/videos
Content-Type: application/json 

{
    "title": "Video cinco",
    "description": "Este é o vídeo de teste de busca",
    "duration": 180
}

###
GET https://node-do-zero-dwb5.onrender.com/videos

###
PUT https://node-do-zero-dwb5.onrender.com/videos/fce190ef-ae87-41f2-919f-6eb6347b75b9
Content-Type: application/json 

{
    "title": "Video 06",
    "description": "Este é o vídeo de teste com novo host",
    "duration": 180
}

###
DELETE https://node-do-zero-dwb5.onrender.com/videos/dde1a5e4-d880-494d-a9d5-e8cdf4418748

